export const firstMock = [
  {
    id: '1',
    corporate: '08',
    store: '999',
    storeName: '123456789012345店',
    date: '9999/99/99',
  },
];

export const secondMock = [
  {
    id: '1',
    classification: '999',
    voucherClass: '9',
    slipNumber: '999999',
    cd: '9',
    suppliers: '99999',
    customerName: 'xxxxxxxxxxxxxxxxxxxxxxx',
  },
];

export const thirdMock = [
  {
    id: 1,
    black: '',
    productName: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    row: '1',
    reason: '9',
    productCode: '999999999999',
    quantity: '10000',
    unitPrice: '1000',
    costAmount: '10000000',
  },
  {
    id: 2,
    black: '',
    productName: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    row: '2',
    reason: '9',
    productCode: '999999999999',
    quantity: '10',
    unitPrice: '1000000',
    costAmount: '10000000',
  },
  {
    id: 3,
    black: '',
    productName: '',
    row: '3',
    reason: '',
    productCode: '',
    quantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 4,
    black: '',
    productName: '',
    row: '4',
    reason: '',
    productCode: '',
    quantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 5,
    black: '',
    productName: '',
    row: '5',
    reason: '',
    productCode: '',
    quantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 6,
    black: '',
    productName: '',
    row: '6',
    reason: '',
    productCode: '',
    quantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 7,
    black: '',
    productName: '',
    row: '7',
    reason: '',
    productCode: '',
    quantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 8,
    black: '',
    productName: '',
    row: '8',
    reason: '',
    productCode: '',
    quantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 9,
    black: '',
    productName: '',
    row: '9',
    reason: '',
    productCode: '',
    quantity: '',
    unitPrice: '',
    costAmount: '',
  },
];
