export const firstMock = [
  {
    id: '1',
    corporationCode: '08',
    storeCode: '999',
    storeName: '123456789012345店',
    inspectionDate: '9999/99/99',
  },
];

export const secondMock = [
  {
    id: '1',
    type: '999',
    slipType: '9',
    slipNumber: '999999',
    cd: '9',
    supplierCode: '99999',
    supplierName: 'xxxxxxxxxxxxxxxxxxxxxxx',
  },
];

export const thirdMock = [
  {
    id: 1,
    black: '',
    productName: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    row: '1',
    reasoningCode: '9',
    productCode: '999999999999',
    productQuantity: '10000',
    unitPrice: '1000',
    costAmount: '10000000',
  },
  {
    id: 2,
    black: '',
    productName: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    row: '2',
    reasoningCode: '9',
    productCode: '999999999999',
    productQuantity: '10',
    unitPrice: '1000000',
    costAmount: '10000000',
  },
  {
    id: 3,
    black: '',
    productName: '',
    row: '3',
    reasoningCode: '',
    productCode: '',
    productQuantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 4,
    black: '',
    productName: '',
    row: '4',
    reasoningCode: '',
    productCode: '',
    productQuantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 5,
    black: '',
    productName: '',
    row: '5',
    reasoningCode: '',
    productCode: '',
    productQuantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 6,
    black: '',
    productName: '',
    row: '6',
    reasoningCode: '',
    productCode: '',
    productQuantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 7,
    black: '',
    productName: '',
    row: '7',
    reasoningCode: '',
    productCode: '',
    productQuantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 8,
    black: '',
    productName: '',
    row: '8',
    reasoningCode: '',
    productCode: '',
    productQuantity: '',
    unitPrice: '',
    costAmount: '',
  },
  {
    id: 9,
    black: '',
    productName: '',
    row: '9',
    reasoningCode: '',
    productCode: '',
    productQuantity: '',
    unitPrice: '',
    costAmount: '',
  },
];
